Repository AY2021S1-CS2103T-T11-2/tp, pull requests merged in 2020-11, with the labels that each got.

#218 Update Ui Class Diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.DG

#219 Add more validation checks for block and room related functions
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/Block.java
  src/main/java/seedu/address/model/person/Room.java
Labels: type.Bug

#234 Update list, clear-event commands in UG
  docs/UserGuide.md
Labels: type.UG

#235 Update ExportSequenceDiagram in DG
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/images/ExportSequenceDiagram.png
Labels: type.DG

#244 UG: fix event's examples
  docs/UserGuide.md
Labels: type.UG

#263 Minor touchups to UG
  docs/UserGuide.md
Labels: type.UG

#264 UG: fix 'computer'
  docs/UserGuide.md
Labels: type.UG

#295 Update DG
  docs/DeveloperGuide.md
Labels: type.DG

#296 DG: update DG
  docs/DeveloperGuide.md
  docs/team/lowjiefeng1998.md
Labels: type.DG
